### ISSUE TITLE
Asset bundling 

### ISSUE THREAD

**Issue by srethira** [shaftoe/api-l3x-in#1]
Is there an example of an asset bundling inside a docker container for lambda function?

**Comment by shaftoe** [comment]
Hello @srethira , can you please elaborate? I'm not sure I understand what you're referring too. Lambda and Docker have different APIs even though their usage can overlap quite. That said, if you want to run a Docker container on AWS you might want to use ECS or EKS services.

You might want to have a look at CDK examples on those pages:
- https://github.com/aws-samples/aws-cdk-examples
- https://cdkpatterns.com/

or ask for CDK help here:
- https://partitions.io/cdk
- https://cdk.dev/

HTH

**Comment by shaftoe** [comment]
@srethira probably this might be of interest too: https://aripalo.com/blog/2020/building-lambda-functions-inside-docker-containers-with-cdk/
